package main

import (
	"strings"
	"testing"
)

// The fixture mirrors the dump's shape: positional rows, numbers stored as strings or numbers,
// a row without produce_time, and the two production columns not at the front.
const fixture = `{"name":"building","index":{"id":[1,"number"],"name":[2,"string"],"para1":[3,"string"],"produce_time":[4,"string"]},
"rows":[[10201001,[10201001,"farm","29280","5000"]],[10100001,[10100001,"hq",null,null]],[761000,[761000,"s1",86400,5000]],[10209001,[10209001,"smelter","29280"]]]}`

func TestParse(t *testing.T) {
	rows, err := parse([]byte(fixture))
	if err != nil {
		t.Fatal(err)
	}
	want := []row{{id: 761000, tickMs: 5000, capS: 86400}, {id: 10201001, tickMs: 5000, capS: 29280}}
	if len(rows) != len(want) {
		t.Fatalf("rows = %+v, want %+v", rows, want)
	}
	for i := range want {
		if rows[i] != want[i] {
			t.Errorf("rows[%d] = %+v, want %+v", i, rows[i], want[i])
		}
	}
}

func TestParseRejects(t *testing.T) {
	cases := map[string]string{
		"other table":    `{"name":"item","index":{},"rows":[]}`,
		"linked column":  `{"name":"building","index":{"produce_time":[1,"string",true],"para1":[2,"string"]},"rows":[[1,["5000","1"]]]}`,
		"missing column": `{"name":"building","index":{"para1":[1,"string"]},"rows":[[1,["1"]]]}`,
		"bad number":     `{"name":"building","index":{"produce_time":[1,"string"],"para1":[2,"string"]},"rows":[[1,["5s","1"]]]}`,
		"no rows":        `{"name":"building","index":{"produce_time":[1,"string"],"para1":[2,"string"]},"rows":[[1,[null,"1"]]]}`,
	}
	for name, src := range cases {
		if _, err := parse([]byte(src)); err == nil {
			t.Errorf("%s: parse succeeded, want an error", name)
		}
	}
}

func TestRender(t *testing.T) {
	code, err := render([]row{{id: 761000, tickMs: 5000, capS: 86400}, {id: 10201001, tickMs: 5000, capS: 29280}}, "39432")
	if err != nil {
		t.Fatal(err)
	}
	src := string(code)
	for _, want := range []string{
		"// Code generated by genproduction from the building data table (table version 39432); DO NOT EDIT.",
		"package game",
		"var productionTable = map[int32]productionLevel{",
		"10201001: {tickMs: 5000, capS: 29280},",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("rendered source lacks %q:\n%s", want, src)
		}
	}
}
