package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// fixture mirrors the real table's layout: "index" gives 1-based column positions, and each row
// is [key, cols]. Here id is column 2 and type column 1, unlike the real table (1 and 5), so a
// parser that hard-codes positions fails.
const fixture = `{"name":"lw_base_visitor_event","index":{"type":[1,"number"],"id":[2,"number"],"para":[3,"string"]},
"rows":[[1001,[1,1001,"200201;1;14;1000"]],[2001,[2,2001,null]],[3115,[3,3115,null]]]}`

func TestParseTableUsesIndexPositions(t *testing.T) {
	got, err := parseTable(strings.NewReader(fixture))
	if err != nil {
		t.Fatalf("parseTable() error = %v", err)
	}
	want := map[int32]int32{1001: 1, 2001: 2, 3115: 3}
	if len(got) != len(want) {
		t.Fatalf("parseTable() = %v, want %v", got, want)
	}
	for id, typ := range want {
		if got[id] != typ {
			t.Errorf("type of %d = %d, want %d", id, got[id], typ)
		}
	}
}

func TestParseTableRejectsBadInput(t *testing.T) {
	cases := map[string]string{
		"wrong table": `{"name":"other","index":{"id":[1,"number"],"type":[2,"number"]},"rows":[[1,[1,2]]]}`,
		"no type col": `{"name":"lw_base_visitor_event","index":{"id":[1,"number"]},"rows":[[1,[1,2]]]}`,
		"key/id skew": `{"name":"lw_base_visitor_event","index":{"id":[1,"number"],"type":[2,"number"]},"rows":[[1,[2,2]]]}`,
		"null type":   `{"name":"lw_base_visitor_event","index":{"id":[1,"number"],"type":[2,"number"]},"rows":[[1,[1,null]]]}`,
		"short row":   `{"name":"lw_base_visitor_event","index":{"id":[1,"number"],"type":[5,"number"]},"rows":[[1,[1,2]]]}`,
		"duplicate":   `{"name":"lw_base_visitor_event","index":{"id":[1,"number"],"type":[2,"number"]},"rows":[[1,[1,2]],[1,[1,3]]]}`,
		"fractional":  `{"name":"lw_base_visitor_event","index":{"id":[1,"number"],"type":[2,"number"]},"rows":[[1,[1,2.5]]]}`,
		"no rows":     `{"name":"lw_base_visitor_event","index":{"id":[1,"number"],"type":[2,"number"]},"rows":[]}`,
	}
	for name, in := range cases {
		if got, err := parseTable(strings.NewReader(in)); err == nil {
			t.Errorf("%s: parseTable() = %v, want an error", name, got)
		}
	}
}

func TestCheckKnownPairs(t *testing.T) {
	good := map[int32]int32{}
	for id, typ := range knownPairs {
		good[id] = typ
	}
	if err := checkKnownPairs(good); err != nil {
		t.Errorf("checkKnownPairs(knownPairs) = %v, want nil", err)
	}
	good[2001] = 1
	delete(good, 1002)
	err := checkKnownPairs(good)
	if err == nil || !strings.Contains(err.Error(), "eventId 2001 has type 1") || !strings.Contains(err.Error(), "eventId 1002 missing") {
		t.Errorf("checkKnownPairs(broken) = %v, want both the changed and the missing pair reported", err)
	}
}

func TestRenderIsFormattedGo(t *testing.T) {
	src, err := render(map[int32]int32{2001: 2, 1001: 1}, "39432", "39516")
	if err != nil {
		t.Fatalf("render() error = %v", err)
	}
	s := string(src)
	for _, want := range []string{
		"// Code generated by internal/game/gen_visitor_types; DO NOT EDIT.\n",
		"table version 39432\n// (byte-identical in live table version 39516).",
		"package game\n",
		"1001: 1,\n\t2001: 2,\n",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("render() output missing %q:\n%s", want, s)
		}
	}
}

func TestRunRejectsTableFailingKnownPairs(t *testing.T) {
	path := filepath.Join(t.TempDir(), "lw_base_visitor_event.json")
	if err := os.WriteFile(path, []byte(fixture), 0o600); err != nil {
		t.Fatal(err)
	}
	out := filepath.Join(t.TempDir(), "out.go")
	if err := run(path, "1", "", out); err == nil {
		t.Fatal("run() = nil, want the known-pair check to reject a three-row table")
	}
	if _, err := os.Stat(out); !os.IsNotExist(err) {
		t.Errorf("run() wrote %s despite failing the known-pair check", out)
	}
}
